name: "Code scanning CodeQL config"

queries:
  - uses: security-and-quality

query-filters:
  - exclude:
      id: cpp/path-injection # disable - ugrep accepts file command line args
  - exclude:
      id: cpp/uncontrolled-process-operation # disable - ugrep may fork process given as command line args
  - exclude:
      id: cpp/user-controlled-bypass # disable - false positives in filename extension check
  - exclude:
      problem.severity:
        - warning # disable code style warnings for C++ noobs
        - recommendation # disable code style notes for C++ noobs
